version: '3.1'

services:
  service01:
    build:
      context: service01
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3100:3000
    volumes:
      - ./service01:/app
    networks:
      - services-demo
    command: node index.js

  service02:
    build:
      context: service02
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3101:3000
    volumes:
      - ./service02:/app
    networks:
      - services-demo
    command: node index.js
    environment:
      - SRV1_HOST=service01:3000

  service03:
    image: qtmsm/service03:v1.0.6
    ports:
      - 3102:3000
    networks:
      - services-demo
    # environment:
    #   - NODE_ENV=development
    #   - MYSQL_HOST=mysql

networks:
  services-demo:
    driver: bridge